In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits


In [2]:
digits= load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(digits.data,digits.target,test_size=.2)

In [27]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

c:\Users\djber\anaconda3\envs\machine_learning\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [28]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9861111111111112

In [29]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9777777777777777

In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [31]:
#KFold(n_splits=3,random_state=None,shuffle=False)
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [33]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [34]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

c:\Users\djber\anaconda3\envs\machine_learning\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [35]:
from sklearn.model_selection import StratifiedGroupKFold


In [36]:
folds = StratifiedGroupKFold(n_splits=3)

In [46]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
 X_train,X_test,y_train,y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index],digits.target[test_index]
 scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
 scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
 scores_rf.append(get_score(RandomForestClassifier(n_estimators=100),X_train,X_test,y_train,y_test))


c:\Users\djber\anaconda3\envs\machine_learning\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\djber\anaconda3\envs\machine_learning\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/lin

In [47]:
scores_l

[0.9277777777777778,
 0.8666666666666667,
 0.9387186629526463,
 0.935933147632312,
 0.9080779944289693]

In [48]:
scores_svm

[0.9694444444444444,
 0.9472222222222222,
 0.9832869080779945,
 0.9888579387186629,
 0.9415041782729805]

In [49]:
scores_rf

[0.9305555555555556,
 0.9111111111111111,
 0.9554317548746518,
 0.9665738161559888,
 0.924791086350975]

In [50]:
from sklearn.model_selection import cross_val_score


In [52]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

c:\Users\djber\anaconda3\envs\machine_learning\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\djber\anaconda3\envs\machine_learning\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/lin

array([0.92153589, 0.94156928, 0.91652755])

In [53]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.93823038, 0.96160267, 0.93823038])

In [59]:
av = cross_val_score(SVC(),digits.data,digits.target,cv=3)

In [57]:
import statistics

In [61]:
average = statistics.mean(av)
average

0.9699499165275459